### ISSUE TITLE
[Bug] Auto merge bot in unstable result in a bug

### ISSUE THREAD

**Issue by DataEraserC** [daeuniverse/flake.nix#118]
duplicated src defined [here](https://github.com/daeuniverse/flake.nix/commit/7fc780a5f49c5c4db832625a1129a35bdf870b1d#diff-2787fb7d822a1fd7a15ac54d438c57f46f72e3c1a2c962518945f05fc5a049d4L92)
after this commit my nixos can not be built

**Comment by oluceps** [comment]
Should be fixed. Could you please test again?

**Comment by oluceps** [comment]
`daed` version of `unstable` is identical to the `main` branch since it has no automatic update.

**Comment by DataEraserC** [comment]
fixed.
thank you!
